### ISSUE TITLE
No work in Laravel 5.5.0

### ISSUE THREAD

**Issue by cristophermr** [tabuna/VestaAPI#7]
Error in the Namespaces, if you change the namespaces you don't cant  publish the vendor.

C:\xampp\htdocs\Hostdroid>php artisan vendor:publish

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Tabuna\VestaAPI\Providers\VestaServiceProvider' not found

**Comment by cristophermr** [comment]
Namespaces fix.
 
Providers:

VestaAPI\Providers\VestaServiceProvider::class,

Alias:
'Vesta' => VestaAPI\Facades\Vesta::class,

The new problem is the publish vendor.

"C:\xampp\htdocs\Hostdroid>php artisan vendor:publish
PHP Warning:  Uncaught ErrorException: require(../config/vesta.php): failed to open stream: No s
uch file or directory in C:\xampp\htdocs\Hostdroid\vendor\laravel\framework\src\Illuminate\Suppo
rt\ServiceProvider.php:59
Stack trace:
#0 C:\xampp\htdocs\Hostdroid\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php
(59): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(../conf...', 'C:
\\xampp\\htdocs...', 59, Array)
#1 C:\xampp\htdocs\Hostdroid\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php
(59): require()
#2 C:\xampp\htdocs\Hostdroid\vendor\tabuna\vesta-api\Providers\VestaServiceProvider.php(27): Ill
uminate\Support\ServiceProvider->mergeConfigFrom('../config/vesta...', 'vesta')
#3 C:\xampp\htdocs\Hostdroid\vendor\tabuna\vesta-api\Providers\VestaServiceProvider.php(14): Ves
taAPI\Providers\VestaServiceProvider->registerConfig()
#4 [internal function]: VestaAPI\Providers\VestaServiceProvider->boot()
#5 C:\xampp\htdocs\Hostdroid\vendor\laravel\framework\src\Illuminate\Con in C:\xampp\htdocs\Host
droid\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php on line 59
PHP Fatal error:  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required
 '../config/vesta.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Hostdroid\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php on line 59


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required '../config/v
  esta.php' (include_path='C:\xampp\php\PEAR')
"

**Comment by tabuna** [comment]
i fix.
